core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
    path('', include('user.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from .views import *
from django.urls import path
from rest_framework.routers import DefaultRouter

router = DefaultRouter()


urlpatterns = [
    path('', home_page, name="home-page"),
    path('service/<int:id>/', service_page, name="service-page"),
    path('service/create/', create_service_page, name="create-service"),
    path('create-service-form/', service_create_form, name="create-service-form"),
    path('service/update/<int:id>/', update_service_page, name="update-service"),
    path('update-service-form/<int:id>/', service_update_form, name="update-service-form"),
    path('service/delete/<int:id>/', service_delete, name="delete-service"),
    path('checkout/<int:id>/', checkout_page, name="checkout-page"),
    path('thank-you/', thank_you_page, name="thank-you-page"),
    path('subscriptions/', subscription_page, name="subscription-page"),

    # ** Api **
    path('api/subscriptions/', SubscriptionView.as_view(), name="subscription-api"),
    path('api/subscriptions/<int:id>/', SubscriptionView.as_view(), name="subscription-api"),
]

router.register(r'api/services', ServiceViewSet)
urlpatterns += router.urls
# List Services: GET /api/services/
# Create Services: POST /api/services/
# Retrieve Services: GET /api/services/{pk}/
# Update Services: PUT /api/services/{pk}/ or PATCH /api/services/{pk}/
# Delete Services: DELETE /api/services/{pk}/

logs/models.py
from django.db import models

# Create your models here.
class OTPLog(models.Model):
    STATUS = [
        ('generated', 'Generated'),
        ('expired', 'Expired'),
        ('verified', 'Verified'),
    ]
    otp = models.CharField(max_length=6)
    email = models.CharField(max_length=30)
    purpose = models.CharField(max_length=30, default="Login")
    content = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default = "generated")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'OTP Log'
        verbose_name_plural = 'OTP Logs'
    
    def __str__(self):
        return f"{self.email} - ({self.otp})"

    def save(self, *args, **kwargs):
        OTPLog.objects.filter(email=self.email, purpose=self.purpose, status='generated').update(status='expired')
        super().save(*args, **kwargs)

services/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    PACKAGES = [
        ('free', 'Free'),
        ('paid', 'Paid')
    ]
    name = models.CharField(max_length=50)
    payment_terms = models.TextField()
    price = models.IntegerField()
    package = models.CharField(max_length=50, choices = PACKAGES, default="free", blank=True)
    tax = models.FloatField()
    image = models.ImageField(upload_to='services/')
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Service"
        verbose_name_plural = "Services"  


# Create your models here.
class Subscription(models.Model):
    service = models.ForeignKey("Service", on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey("user.User", on_delete=models.CASCADE, related_name="subscriptions")
    razorpay_payment_id = models.CharField(max_length=250, null=True, blank=True)
    razorpay_order_id = models.CharField(max_length=250, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=250, null=True, blank=True)
    payment_status = models.CharField(max_length=250, default="Pending")
    amount = models.FloatField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = "Subscription"
        verbose_name_plural = "Subscriptions"  




  

services/forms.py
from .models import *
from django import forms

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'image', 'payment_terms', 'price', 'package', 'tax', 'is_active')
 

services/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from rest_framework import viewsets, permissions
from rest_framework.views import APIView
from rest_framework.response import Response


from .serializers import*
from .models import *
from .forms import ServiceForm

import razorpay
import traceback
import environ
env = environ.Env()

# Create your views here.

@login_required
def home_page(request):
    service = request.GET.get('service', None)
    page = request.GET.get('page')
    if service is None:
        service_obj = Service.objects.all().order_by('-date')
        if not request.user.is_superuser:
            service_obj= service_obj.filter(is_active=True)
        paginator = Paginator(service_obj, 3) 
        page_obj = paginator.get_page(page)
        return render(request, 'home.html', {'page_obj':page_obj})
    else:
        service_obj = Service.objects.filter(name__icontains = service).order_by('-date')
        if not request.user.is_superuser:
            service_obj= service_obj.filter(is_active=True)
        data = [{
                'id':service_obj.id, 
                'name':service_obj.name, 
                'image':service_obj.image.url, 
                'price':service_obj.price, 
                'is_active':service_obj.is_active
                } for service_obj in service_obj]
        return JsonResponse({'page_obj':data})
    

@login_required
def subscription_page(request):
    page = request.GET.get('page')
    subscription_obj = Subscription.objects.filter(payment_status__in = ['success', 'failed']).order_by('-date')
    if not request.user.is_superuser:
        subscription_obj= subscription_obj.filter(user=request.user)
    paginator = Paginator(subscription_obj, 10) 
    page_obj = paginator.get_page(page)
    return render(request, 'subscription.html', {'page_obj':page_obj})


@login_required
def service_page(request, id):
    try:
        service_obj = Service.objects.get(id=id)
        if not request.user.is_superuser:
            service_obj = Service.objects.get(id=id,is_active=True)
        subscribed_obj = request.user.subscriptions.filter(service =service_obj)
        if subscribed_obj.exists():
            subscribed = True
        else:
            subscribed = False
        return render(request, 'service.html', {'service':service_obj, 'subscribed':subscribed})
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, "Invalid Service Request")
        return redirect('/')
                

@login_required
def create_service_page(request):
    if not request.user.is_superuser:
        messages.error(request, "Doesn't have Required Permission")
        return redirect('/')
    form = ServiceForm()
    return render(request, 'service_create.html', {'form':form})

    
@login_required
def service_create_form(request):
    name = request.POST.get('name')
    payment_terms = request.POST.get('payment_terms')
    price = request.POST.get('price')
    package = request.POST.get('package')
    tax = request.POST.get('tax')
    is_active = request.POST.get('is_active')
    try:
        if not request.user.is_superuser or request.method != 'POST':
            raise ValueError('Creation Failed')
        print("FIRST CHECK::")
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Service Created Successfully")
            print("SECOND CHECK::")
            return redirect("/")
        else:
            raise ValueError(form.errors)
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, str(e))
        form = ServiceForm(initial={
            'name': name, 
            'payment_terms': payment_terms, 
            'price': price, 
            'package': package, 
            'tax':tax, 
            'is_active':is_active
            })
        return render(request, 'service_create.html', {'form':form})       


@login_required
def update_service_page(request, id):
    try:
        if not request.user.is_superuser:
            raise ValueError("Not allowed")
        obj = Service.objects.get(id=id)
        form = ServiceForm(initial={
            'name': obj.name, 
            'payment_terms': obj.payment_terms, 
            'price': obj.price, 
            'package': obj.package, 
            'tax':obj.tax, 
            'image':obj.image.url, 
            'is_active':obj.is_active
            })
        return render(request, 'update_service.html', {'form':form, 'service':id})
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, "Failed to Update Service")
        return redirect(f"/service/{id}/")

    
@login_required
def service_update_form(request, id):
    name = request.POST.get('name')
    payment_terms = request.POST.get('payment_terms')
    price = request.POST.get('price')
    package = request.POST.get('package')
    tax = request.POST.get('tax')
    is_active = request.POST.get('is_active')
    try:
        if not request.user.is_superuser or request.method != 'POST':
            raise ValueError('Updation Failed')
        service = Service.objects.get(id=id)

        form = ServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()
            messages.success(request, "Service updated Successfully")
            return redirect(f"/service/{id}/")
        else:
            raise ValueError(form.errors)
    except Exception as e:
        messages.error(request, str(e))
        form = ServiceForm(initial={
            'name': name, 
            'payment_terms': payment_terms, 
            'price': price, 
            'package': package, 
            'tax':tax, 
            'is_active':is_active
            })
        return render(request, 'update_service.html', {'form':form, 'service':id})
 

@login_required
def service_delete(request, id):
    try:
        if not request.user.is_superuser:
            raise ValueError("Permission Denied")
        Service.objects.get(id=id).delete()
        messages.success(request, "Service Deleted Successfully")
        return redirect("/")
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, "Service Deletion Failed")
        return redirect(f"/service/{id}/")
        
    
@login_required
def checkout_page(request, id):
    try:
        service_obj = Service.objects.filter(id=id).first()
        if not service_obj:
            raise ValueError("Can't find the service")
        verify_obj = Subscription.objects.filter(user = request.user, service = service_obj, payment_status="success").order_by('-date')
        if verify_obj.exists():
            messages.success(request, 'Service is already Subscribed')
            return redirect(f"/service/{id}/")

        amount_inc_tax = round((int(service_obj.price) + (int(service_obj.price) * float(service_obj.tax) / 100)))
        
        client = razorpay.Client(auth=(env('KEY'), env('SECRET_KEY')))
        if not client:
            raise ValueError("Error while creating client")

        order_data = { "amount": (amount_inc_tax * 100), "currency": "INR", "receipt": f"subscription_order_{service_obj.id}" }
        payment = client.order.create(data=order_data)
        if not payment:
            raise ValueError("Error while creating order")

        sub_obj, _ = Subscription.objects.get_or_create(
            user = request.user,
            service = service_obj,
            payment_status = "pending"
        )
        sub_obj.amount = amount_inc_tax
        sub_obj.razorpay_order_id = payment['id']
        sub_obj.save()

        data={
            'key':env('KEY'),
            'subscription':sub_obj,
            'payment':payment
        }
        return render(request, 'checkout.html', {'data':data})
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, 'Error in Service Checkout')
        return redirect(f"/service/{id}/")


@login_required
def thank_you_page(request):
    razorpay_payment_id = request.GET.get('razorpay_payment_id')
    razorpay_order_id = request.GET.get('razorpay_order_id')
    razorpay_signature = request.GET.get('razorpay_signature')

    sub_obj = Subscription.objects.filter(razorpay_order_id = razorpay_order_id).first()
    if not sub_obj:
        messages.error(request, 'Payment Failed, cannot find the required IDs')
        return redirect("/")
    try:
        data={}
        if razorpay_payment_id and razorpay_order_id and razorpay_signature:
            sub_obj.razorpay_payment_id = razorpay_payment_id
            sub_obj.razorpay_signature = razorpay_signature
            sub_obj.payment_status = "success"
            sub_obj.save()

            data["response"]="success"
        else:
            reason = request.GET.get('reason')
            description = request.GET.get('description')
            print("Payment failed:::", reason, description)
            sub_obj.payment_status = "failed"
            sub_obj.save()

            data["response"]="failed"
            data["reason"]=reason
        return render(request, 'thank_you.html', {'data':data})
    except Exception as e:
        print(str(e), traceback.format_exc())
        messages.error(request, str(E))
        return redirect("/")




# ** APIs **
class ServiceViewSet(viewsets.ModelViewSet):
    queryset = Service.objects.all()
    serializer_class = ServiceSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_permissions(self):
        if self.action in ['create', 'destroy', 'update', 'partial_update']:

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IT Services</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/authentication.css' %}" />

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="/">IT Services</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/subscriptions/">Subscriptions</a>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="/login/"> Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/register/">Register</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="/logout/">Logout</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <div>
        {% block content %}{% endblock content %}

      </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/base.js' %}"></script>

  </body>
</html>

templates/register.html
{% extends "base.html" %}
{% load static %}


{% block content %}
{% comment %} TODO SUCCESS MESSAGE  {% endcomment %}

    
{% if messages %}
    <div class="position-fixed top-25 w-100">
        {% for message in messages %}
            {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Well Done!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Oops!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
<div class="my_form  py-5">
    <div class="form-cont">        
        <div class="form-box">
            <form class="form-block" method="post"  action="{% url 'user-register-form' %}" >
                {% csrf_token %}     
                {% for fo in form %}
                    {% if fo.name == "fullname" %}
                        <div class="form-group mt-3" >
                            <input type="text" name="fullname" maxlength="50" class="form-fields " required="" id="id_fullname"  value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Full Name">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "email" %}
                        <div class="d-flex flex-row mt-3" style="justify-content:space-between;">
                            <div class="form-group" style="width:70%;">
                                <input type="email" name="email" maxlength="30" class="form-fields " required="" id="id_email" value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Email">
                                <div id="timer" style="font-size:0.7rem;"></div>
                            </div> 
                            <div id="get-otp" class="form-group button ml-2" style="width:27%;margin-top:0vw;justify-content:unset;">
                                <button id="get_otp-button" type="button"  class="btn btn-primary"  data-loading-text="Submitting...">Get OTP</button>
                            </div>
                            <div id="otp-field" class="form-group  d-none ml-2" style="width:27%;margin-top:0vw;">
                                <input type="text" name="otp" minlength="6" maxlength="6" class="form-fields" required id="id_otp" placeholder="OTP" pattern="\d*" title="Please enter a 6-digit number OTP">
                            </div> 
                        </div>
                        {{fo.errors}}
                    {% elif fo.name == "mobile" %}
                        <div class="form-group mt-3">
                            <input type="text" name="mobile" minlength="10" maxlength="10" class="form-fields " required="" id="id_mobile" value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Mobile Number" pattern="[6-9][0-9]*" title="Please enter a 10-digit mobile number, starting with 6, 7, 8, or 9">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "address" %}
                        <div class="form-group  mt-3">
                            <input type="text" name="address" maxlength="50" class="form-fields " required="" id="id_address"  value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="address">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "password" %}    
                        <div class="form-group mt-3">
                            <div class="password-field">
                                <input type="password" name="password" minlength="8" maxlength="20" class="form-fields " value="{% if fo.value %}{{fo.value}}{% endif %}" required="" id="id_password" placeholder="Password">
                                <span class="fa fa-eye-slash"></span>
                            </div>
                        </div> 
                        {{fo.errors}}
                    {% endif %}
                {% endfor %}
                <div class="button">
                    <button name="register_form" type="submit" value="Register" class="btn btn-primary btn-lg" data-loading-text="Submitting...">Submit</button>
                </div>
            </form>
            {% if not request.user.is_authenticated %}
                <div class="sign-up">
                    <p>Already have an account?<a href="/login/">login</a></p>
                </div>
            {% endif %}
        </div>
    </div>
</div>  
{% endblock content %}

templates/service_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if messages %}
    <div class="position-fixed top-25 w-250">
        {% for message in messages %}
            {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Well Done!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Oops!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
    
<div class="my_form  py-5">
    <div class="form-cont"> 
        <h2 style="d-block;text-align:center;font-weight:800;color:#717171;">Create Service</h2>
       
        <div class="form-box">
            <form class="form-block" method="post"  action="{% url 'create-service-form' %}" enctype="multipart/form-data">
                {% csrf_token %}     
                {% for fo in form %}
                    {% if fo.name == "name" %}
                        <div class="form-group mt-3" >
                            <input type="text" name="name" maxlength="50" class="form-fields " required="" id="id_name" placeholder="Service Name">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "image" %}
                        <div class="form-group mt-3" >
                            <input type="file" name="image" accept="image/*" class="form-fields " required="" id="id_image" >
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "payment_terms" %}
                        <div class="form-group mt-3" >
                            <textarea name="payment_terms" class="form-fields" required id="id_payment_terms" placeholder="Payment Terms" rows="50" style="height:11rem"></textarea>
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "price" %}
                        <div class="form-group mt-3" >
                            <input type="number" name="price" required=""  class="form-fields " id="id_price" placeholder="Price">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "tax" %}
                        <div class="form-group mt-3" >
                            <input type="number" name="tax" step="any"  class="form-fields " required="" id="id_tax" placeholder="Tax">
                        </div> 
                        {{fo.errors}}
                    {% elif fo.name == "package" %}
                        <div class="form-group mt-3">
                            <select name="package" class="form-fields" id="id_package">
                                {% for choice in fo.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == fo.value %}selected{% endif %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "is_active" %}
                        <div class="form-group mt-3" style="width:100%;display:flex;flex-direction:row !important;">
                            <input type="checkbox" name="is_active" class="form-fields"  style="width:2rem;" id="id_is_active" {% if fo.value %}checked{% endif %}>
                            <label for="id_is_active" style="width:16rem;padding-left:1rem">Active/In-Active</lable>
                        </div>
                        {{ fo.errors }}
                    {% endif %}
                {% endfor %}
                <div class="button">
                    <button name="register_form" type="submit" value="Register" class="btn btn-primary btn-lg" data-loading-text="Submitting...">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div> 
{% endblock content %}

templates/update_service.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if messages %}
    <div class="position-fixed top-25 w-100">
        {% for message in messages %}
            {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Well Done!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% elif message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show  w-75 mx-auto " role="alert" style="z-index:999;">
                    <strong>Oops!</strong> {{message|linebreaks}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}
    
<div class="my_form  py-5">
    <div class="form-cont ">        
        <h2 style="d-block;text-align:center;font-weight:800;color:#717171;">Update Service</h2>
        <div class="form-box">
            <form class="form-block" method="post" enctype="multipart/form-data" action="{% url "update-service-form" id=service %}">
                {% csrf_token %}
                {% for fo in form %}
                    {% if fo.name == "name" %}
                        <div class="form-group mt-3">
                            <input type="text" name="name" maxlength="50" class="form-fields" required="" id="id_name" value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Service Name">
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "payment_terms" %}
                        <div class="form-group mt-3">
                            <textarea name="payment_terms" class="form-fields" required id="id_payment_terms" placeholder="Payment Terms" rows="50" style="height:11rem">{% if fo.value %}{{fo.value}}{% endif %}</textarea>
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "price" %}
                        <div class="form-group mt-3">
                            <input type="number" name="price" class="form-fields" required="" id="id_price" value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Price">
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "package" %}
                        <div class="form-group mt-3">
                            <select name="package" class="form-fields" id="id_package">
                                {% for choice in fo.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == fo.value %}selected{% endif %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "tax" %}
                        <div class="form-group mt-3">
                            <input type="number" name="tax" class="form-fields" id="id_tax" value="{% if fo.value %}{{fo.value}}{% endif %}" placeholder="Tax">
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "image" %}
                        <div class="form-group mt-3">
                            <input type="file" name="image" class="form-fields" id="id_image">
                            {% if fo.value %}
                                <img src="{% if fo.value %}{{fo.value}}{% endif %}" alt="Current img" style="max-width: 100px; max-height: 100px;border-radius:0.5rem;margin-top:0.5rem;">
                            {% endif %}
                        </div>
                        {{ fo.errors }}
                    {% elif fo.name == "is_active" %}
                        <div class="form-group mt-3" style="width:100%;display:flex;flex-direction:row !important;">
                            <input type="checkbox" name="is_active" class="form-fields"  style="width:2rem;" id="id_is_active" {% if fo.value %}checked{% endif %}>
                            <label for="id_is_active" style="width:16rem;padding-left:1rem">Active/In-Active</lable>
                        </div>
                        {{ fo.errors }}
                    {% endif %}
                {% endfor %}
                <input type="number" name="service" class="d-none" id="id_service" value="{{ service }}">

                <div class="button">
                    <button type="submit" class="btn btn-primary btn-lg" data-loading-text="Submitting...">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div> 
{% endblock content %}